services:
  db:
    image: postgres:18-alpine
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${DB_NAME?Variable not set}
      POSTGRES_USER: ${DB_USER?Variable not set}
      POSTGRES_PASSWORD: ${DB_PASSWORD?Variable not set}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - katharsis-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    command: start-dev
    env_file:
      - .env
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: "false"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - katharsis-net

  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${ENVIRONMENT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${KEYCLOAK_ISSUER}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: ${KEYCLOAK_ISSUER}/protocol/openid-connect/certs
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 15s
    networks:
      - katharsis-net

  frontend:
    build: ./frontend
    env_file:
      - .env
    networks:
      - katharsis-net

volumes:
  postgres_data:

networks:
  katharsis-net:
    driver: bridge
